POST http://localhost:8080/api/user/registration
Content-Type: application/json

{
    "username" : "siiulan79@gmail.com",
	"password" : "123456",
	"firstname" : "Test",
	"lastname" : "Test"
}

###

POST http://localhost:8080/api/user/registration
Content-Type: application/json

{
    "username":"123@com",
	"password":"123",
	"firstname":"sb",
	"lastname":"ni"
}

###

POST http://localhost:8080/api/user/login
Content-Type: application/json

{
    "username": "r63gao@uwaterloo.ca",
	"password": "admin"
}

###

POST http://localhost:8080/api/user/login
Content-Type: application/json

{
    "username" : "siiulan79@gmail.com",
	"password" : "123456"
}

###

POST http://localhost:8080/api/user/reset/forgotPassword
Content-Type: application/json

{
    "username" : "siiulan79@gmail.com"
}

###

POST http://localhost:8080/api/user/reset/request/0
Content-Type: application/json

{
	"newPassword" : "newPassword",
	"verifyToken" : "0"
}

###

GET http://localhost:8080/api/user/test/email
Content-Type: application/json

{
    "email" : "siiulan79@gmail.com"
}

###
POST http://localhost:8080/api/user/verify/resend
Content-Type: application/json

{
    "email" : "siiulan79@gmail.com"
}

###
POST http://localhost:8080/api/user/instructor/getClass
Content-Type: application/json

{
    "user_ID" : "2"
}

### class existed, student haven't been enrolled in this class and the code is right
POST http://localhost:8080/api/user/student/addclass
Content-Type: application/json

{
    "user_ID" : "6",
	"class_NUMBER" : "YES100",
	"invitation_CODE" : "123456"
}

###class existed, student haven't been enrolled in this class and the code is false
POST http://localhost:8080/api/user/student/addclass
Content-Type: application/json

{
    "user_ID" : "5",
	"class_NUMBER" : "YES100",
	"invitation_CODE" : "123"
}

###
POST http://localhost:8080/api/user/student/classes
Content-Type: application/json

{
    "user_ID" : "1"

}
###
POST http://localhost:8080/api/user/student/classes/class
Content-Type: application/json

{
    "class_ID" : "4"

}
###
POST http://localhost:8080/api/user/student/test
Content-Type: application/json

{
    "user_ID" : "1",
	"user_ROLE" : "student"

}