POST http://localhost:8080/api/user/registration
Content-Type: application/json

{
    "username" : "test@gmail.com",
	"password" : "123456",
	"invitation_code" : "",
	"firstname" : "Test",
	"lastname" : "Test"
}



###

POST http://localhost:8080/api/user/login
Content-Type: application/json

{
    "username": "r63gao@uwaterloo.ca",
	"password": "admin"
}

###

POST http://localhost:8080/api/user/login
Content-Type: application/json

{
    "username" : "test@gmail.com",
	"password" : "123456"
}